apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-definitions
  labels:
    app.kubernetes.io/name: {{ include "tg-global-messaging-platform-rabbitmq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  load_definition.json: |
{{ .Files.Get "files/definitions.json" | indent 4 }}