auth:
  username: user
  password: admin123
  vhost: tg-message-service

loadDefinition:
  enabled: true
  existingSecret: rabbitmq-definitions

extraPlugins: "rabbitmq_shovel rabbitmq_shovel_management rabbitmq_federation rabbitmq_federation_management"

ingress:
  enable: true
  hostname: <domain_name>
  annotations:
    extrnal-dns.alpha.kubernetes.io/hostname: <domain_name>
    nginx.ingress.kubernetes.io/rewrite-target: /
  tls: false #Need to enable it true when we are are using TLS certificate 