apiVersion: v2
name: tg-global-messaging-platform-rabbitmq
description: A Helm chart for TG Global Messaging Platform RabbitMQ
type: application
version: 1.3.0
appVersion: "1.3.0" # Adjust if needed
dependencies:
  - name: rabbitmq
    version: 16.0.2 # Match Bitnami's chart version you want
    repository: https://charts.bitnami.com/bitnami
annotations:
  artifacthub.io/changes: "## [1.3.0](https://github.com/TopGolf/tg-global-messaging-platform-rabbitmq/compare/v1.2.0...v1.3.0) (2025-05-07)\n\n\n### \U0001F680 Features\n\n* [REL-3022](https://topgolf.atlassian.net/browse/REL-3022) updates to deploy in venue (#9) ([45120a8](https://github.com/TopGolf/tg-global-messaging-platform-rabbitmq/commit/45120a8da2872dab9530c3b5eb315c8a284b651c))\n\n"
