loadDefinition:
  enabled: true
  existingSecret: load-definition
extraConfigurations: |
  load_definition = /app/load_definition.json
# existingSecret: rabbitmq-definitions

auth:
  username: user
  password: bitnami
  vhost: tg-message-service

persistence:
  enabled: true
  storageClass: ""
  size: 8Gi

service:
  type: ClusterIP

extraPlugins: "rabbitmq_shovel rabbitmq_shovel_management rabbitmq_federation rabbitmq_federation_management"

ingress:
  enable: true
  hostname: <domain_name>
  annotations:
    extrnal-dns.alpha.kubernetes.io/hostname: <domain_name>
    nginx.ingress.kubernetes.io/rewrite-target: /
  tls: false #Need to enable it true when we are are using TLS certificate 

extraConfigmapMounts:
- name: rabbiit-definitions
  mountPath: /app/definitions/
  configMap: load-definition
  subPath: ""
  readOnly: true
