rabbitmq:
  auth:
    username: admin
    password: bitnami
    erlangCookie: xRDO1zTbFBkjWhfAS6cYmfGPrgZqr2mjD02DZ6gvpZgf
  containerSecurityContext:
    runAsGroup: 0
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true
    capabilities:
      drop: []
    seccompProfile:
      type: Unconfined
  extraConfiguration: |-
    hipe_compile = false
    load_definitions = /app/load_definition.json
    stomp.default_user = guest
    stomp.default_pass = guest
    web_stomp.listen = 15674
  extraPlugins: "rabbitmq_shovel rabbitmq_shovel_management rabbitmq_federation rabbitmq_federation_management rabbitmq_stomp rabbitmq_web_stomp"
  global:
    compatibility:
      openshift:
        adaptSecurityContext: disabled
  ingress:
    enabled: true
    extraHosts:
    - name: rabbitmq
      path: /
    hostname: tg-gms-rabbit
    tls: false #Need to enable it true when we are are using TLS certificate
  loadDefinition:
    enabled: true
    existingSecret: rabbitmq-definitions
  persistence:
    enabled: true
    storageClass: ""
    size: 8Gi
  replicaCount: 3
  resourcesPreset: none
  service:
    type: ClusterIP
    ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
    - name: webstomp
      port: 15674
      targetPort: 15674
