rabbitmq:
  loadDefinition: true
  definitionsSource: secret
  existingSecret: rabbitmq-definitions

  auth:
    username: user
    password: admin123
    vhost: tg-message-service
    erlangCookie: secretcookie

  persistence:
    enabled: true
    storageClass: ""
    size: 8Gi

  service:
    type: ClusterIP

extraPlugins: "rabbitmq_shovel rabbitmq_shovel_management rabbitmq_federation rabbitmq_federation_management"

  ingress:
    enable: true
    hostname: <domain_name>
    annotations:
      extrnal-dns.alpha.kubernetes.io/hostname: <domain_name>
      nginx.ingress.kubernetes.io/rewrite-target: /
    tls: false #Need to enable it true when we are are using TLS certificate 